### ISSUE TITLE
examples / cli help

### ISSUE THREAD

**Issue by tdensmore** [tryretool/retool-cli#15]
My company uses reTool and I was hoping to use the CLI to drive some automation. 

I am running reTool from a Docker container to prevent users from having to install NPM, so the web auth doesn't work.  However I did manage to `login` using the scraped tokens.

I would like to set default values for new internal organizations using the CLI. However it is unclear to me how to interact with apps / dbs from the command line. 

`retool apps --list` shows me 4 apps. Now what?

`retool db -l` gives me `No tables found.` although I see some in the UI.

Are there examples or CLI docs you can point me to?

**Comment by PeteTheHeat** [comment]
Hey @tdensmore, thanks for trying out the CLI! 

Full disclosure: the CLI is pretty new and may not support everything you might expect it to. What kind of values were you hoping to set for new orgs? 

> Are there examples or CLI docs you can point me to?

The only documentation that exists right now is `retool help` or `retool <command> --help`.

> `retool db -l` gives me No tables found. although I see some in the UI.

That is unexpected. You're definitely logged in to the same Retool account, correct? Does `retool apps -l` and `retool workflows -l` show what you would expect to see?

**Comment by tdensmore** [comment]
Sorry for the delay. I did not see the notification.

Yes `retool apps -l` and `retool workflows -l` show me the things I would expect.
One of the apps that is shown is the app I would like to use. How do I do that?

Additionally the command `retool db -l` says: "No tables found."

I must be doing something wrong...

**Comment by PeteTheHeat** [comment]
> One of the apps that is shown is the app I would like to use. How do I do that?

CLI doesn't currently support "using" an app like you might expect from the browser. What kind of automation were you hoping to drive?

> I must be doing something wrong...

Not necessarily! For reference, here's what I would expect to see:
<img width="1280" alt="Screenshot 2023-11-02 at 11 00 31 AM" src="https://github.com/tryretool/retool-cli/assets/6011080/10a10cfb-7156-4d4e-a3ab-021c9bd9382a">
