### ISSUE TITLE
Feature Request: Allow importing / exporting Toolscript from an app

### ISSUE THREAD

**Issue by amrawadk** [tryretool/retool-cli#18]
exporting tool script is an action I need to use often when I need to search across the app (both components and raw queries), having it accessible through the CLI would immensely improve the flow.

**Comment by PeteTheHeat** [comment]
Hey @amrawadk, very valid request! 

I was able to easily add JSON exporting in https://github.com/tryretool/retool-cli/commit/f064de7e033a5aa1c689963ac4adde4db2812165. If you update to the latest version (1.0.26) via `npm install -g retool-cli`, you should be able to use the new command.

<img width="617" alt="Screenshot 2024-02-29 at 2 48 53 PM" src="https://github.com/tryretool/retool-cli/assets/6011080/90802159-5bbe-41eb-9719-fc5708247175">

Unfortunately, toolscript exporting is a little trickier, that code is more closely tied to the Retool frontend. Hope JSON exporting is enough for your use case!
